DROP TABLE konto;
CREATE TABLE konto(kid NUMBER, kname VARCHAR(32), balance NUMBER, PRIMARY KEY (kid));

INSERT INTO konto VALUES (-1, 'BANK', 100000);
INSERT INTO konto VALUES (0, 'KING', 500000);
INSERT INTO konto VALUES (1, 'SCOTT', 200000);
INSERT INTO konto VALUES (2, 'ANTON', 200000);
INSERT INTO konto VALUES (3, 'HERBERT', 0);

COMMIT;
